version: "3.8"

services:
    # Main bot service
    apkonsult:
        container_name: apkonsult
        image: ghcr.io/sombody101/apkonsult:latest # Specify image name (for watchtower)
        volumes:
            - /mnt/AppStorage/apkonsult-bot/0vol:/app/0vol
        environment:
            # Prevents CultureNotFoundException on container start
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
            - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
        restart: unless-stopped
        user: 1001:1001

    # Auto updater
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 240 # Four ~~hours~~ *minutes*

    # Music server (I have no idea how I managed this on past bots. I think I might have just manually spawned a Java instance?)
    lavalink:
        image: fredboat/lavalink:latest
        container_name: lavalink
        restart: unless-stopped
        ports:
            - "2333:2333"
        environment:
            - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
            - LAVALINK_SERVER_PORT=${LAVALINK_SERVER_PORT:-2333}
            - LAVALINK_SERVER_ENCODING=${LAVALINK_SERVER_ENCODING:-UTF-8}
            - JAVA_OPTS=-Xmx512M -Xms256M
        volumes:
            - ./lavalink-data:/opt/Lavalink/data
